# -*- coding: utf-8 -*-
"""GDP Analysis - Compare GDP Growth Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTsG7Vb4wCi--8kojZnwCbO_ixgjhtuU

# Compare GDP Growth Comparison

Instead Of Country Code We Can Also Use Country Name
"""

import os
import pandas as pd
import plotly.express as px
import plotly.offline as pyo

df = pd.read_csv('gdp.csv')

final_data = []

for country_name in df['Country Name'].unique():

  df_pr = df[df['Country Name'] == country_name]

  data = df_pr.values

  gdp_change = [0]

  for i in range(1,len(data)):

    prev = data[i-1][3]
    cur = data[i][3]

    gdp_change.append(round(((cur - prev) / prev)*100,2))

  df_pr = df_pr.assign(GDP_Percent = gdp_change)
  final_data.append(df_pr)

df = pd.concat(final_data, axis = 0)

df.head()

def compare_gdp(lst):

  dfs = []
  for i in lst:
      dfs.append(df[df['Country Code'] == i])

      df_pr = pd.concat(dfs, axis = 0)

      fig = px.line(df_pr, x = 'Year', y = 'GDP_Percent', title = 'GDP Analysis Based - ' + '|'.join(lst), color = 'Country Name')
      pyo.plot(fig, filename = '|'.join(lst) + '.html')

compare_gdp(['IND','USA'])

"""## GDP_Percent Growth Comparies Of All The Countries



"""

fig = px.line(df, x = 'Year', y = 'GDP_Percent', title = 'GDP_Percent Growth ALL Countries', color = 'Country Name')
pyo.plot(fig, filename = 'GDP Growth.html')

"""## GDP_Percent Growth Of All The Countries Individual"""

# Taking Country Name Would Be Better
os.mkdir('GDP Growth Individual')

for country_name in df['Country Code'].unique():

    df_pr = df[df['Country Code'] == country_name]

    fig = px.line(df_pr, x = 'Year', y = 'GDP_Percent', title = country_name)
    pyo.plot(fig, filename = 'GDP Growth Individual/' + country_name + '.html', auto_open = False)

"""# IMP Checking For Outlier Missing Data Technq

#### By Running The Below Code We Can See Majority Of Data Lays Between 57 Years By That we can say in many countries we have missing data
"""

# We Have Latest Data Of 2016 we can say 2016 - 57 = 1959 year

for country_name in df['Country Name'].unique():
    df_pr = df[df['Country Name'] == country_name]
    print(country_name, len(df_pr))

"""# Hence We Can Say GDP Growth btw 1960 - 2016"""

dfs =[]

for country_name in df['Country Name'].unique():
    df_pr = df[df['Country Name'] == country_name]

    if (len(df_pr) == 57):
      dfs.append(df_pr) # Here We Are Getting a list of countries which have 57 years of data.

df_pr = pd.concat(dfs, axis = 0)

df_pr

# Here We Have Generated The Graph Based On 57 year data removeing outlier (missing data).

fig = px.line(df_pr, x = 'Year', y = 'GDP_Percent', title = 'GDP_Percent Growth', color = 'Country Name')

pyo.plot(fig, filename = 'GDP Growth 1960-2016.html', auto_open = False)

